/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace EncryptedExamScore {
  export type AuditLogStruct = {
    user: AddressLike;
    action: string;
    timestamp: BigNumberish;
    actionId: BytesLike;
  };

  export type AuditLogStructOutput = [
    user: string,
    action: string,
    timestamp: bigint,
    actionId: string
  ] & { user: string; action: string; timestamp: bigint; actionId: string };
}

export interface EncryptedExamScoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "TIME_LOCK_DURATION"
      | "VERSION"
      | "approveEmergencyAction"
      | "auditLogs"
      | "deleteMyScore"
      | "emergencyApprovals"
      | "enableUpgrades"
      | "executeOwnershipTransfer"
      | "getAuditLog"
      | "getAuditLogCount"
      | "getAuditLogsByAction"
      | "getAuditLogsByUser"
      | "getConstants"
      | "getEmergencyApprovalCount"
      | "getHealthStatus"
      | "getImplementation"
      | "getMyScore"
      | "getMyScoreCount"
      | "getTimeLockRemaining"
      | "hasApproved"
      | "hasScore"
      | "implementation"
      | "initiateOwnershipTransfer"
      | "owner"
      | "pause"
      | "paused"
      | "protocolId"
      | "scoreCount"
      | "setImplementation"
      | "submitBatchScores"
      | "submitScore"
      | "timeLockedActions"
      | "transferOwnership"
      | "unpause"
      | "updateScore"
      | "upgradeEnabled"
      | "validateBatch"
      | "validateScore"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BatchScoresSubmitted"
      | "OwnershipTransferred"
      | "Paused"
      | "ScoreDeleted"
      | "ScoreSubmitted"
      | "ScoreUpdated"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "TIME_LOCK_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "VERSION", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "approveEmergencyAction",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "auditLogs",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteMyScore",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyApprovals",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "enableUpgrades",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeOwnershipTransfer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAuditLog",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAuditLogCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAuditLogsByAction",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAuditLogsByUser",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getConstants",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEmergencyApprovalCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getHealthStatus",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getImplementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMyScore",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMyScoreCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTimeLockRemaining",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasApproved",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "hasScore", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "implementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initiateOwnershipTransfer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "scoreCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setImplementation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitBatchScores",
    values: [BytesLike[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "submitScore",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "timeLockedActions",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateScore",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "validateBatch",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "validateScore",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "TIME_LOCK_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "VERSION", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "approveEmergencyAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "auditLogs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deleteMyScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyApprovals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enableUpgrades",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeOwnershipTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAuditLog",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAuditLogCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAuditLogsByAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAuditLogsByUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getConstants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEmergencyApprovalCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHealthStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMyScore", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMyScoreCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTimeLockRemaining",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasScore", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "implementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initiateOwnershipTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "scoreCount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitBatchScores",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "timeLockedActions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateScore",
    data: BytesLike
  ): Result;
}

export namespace BatchScoresSubmittedEvent {
  export type InputTuple = [
    user: AddressLike,
    count: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [user: string, count: bigint, timestamp: bigint];
  export interface OutputObject {
    user: string;
    count: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [
    previousOwner: AddressLike,
    newOwner: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    previousOwner: string,
    newOwner: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [account: string, timestamp: bigint];
  export interface OutputObject {
    account: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScoreDeletedEvent {
  export type InputTuple = [user: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [user: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScoreSubmittedEvent {
  export type InputTuple = [
    user: AddressLike,
    scoreIndex: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    scoreIndex: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    scoreIndex: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScoreUpdatedEvent {
  export type InputTuple = [
    user: AddressLike,
    scoreIndex: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    scoreIndex: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    scoreIndex: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [user: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [user: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EncryptedExamScore extends BaseContract {
  connect(runner?: ContractRunner | null): EncryptedExamScore;
  waitForDeployment(): Promise<this>;

  interface: EncryptedExamScoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  TIME_LOCK_DURATION: TypedContractMethod<[], [bigint], "view">;

  VERSION: TypedContractMethod<[], [string], "view">;

  approveEmergencyAction: TypedContractMethod<
    [actionId: BytesLike],
    [void],
    "nonpayable"
  >;

  auditLogs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, string] & {
        user: string;
        action: string;
        timestamp: bigint;
        actionId: string;
      }
    ],
    "view"
  >;

  deleteMyScore: TypedContractMethod<[], [void], "nonpayable">;

  emergencyApprovals: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  enableUpgrades: TypedContractMethod<[], [void], "nonpayable">;

  executeOwnershipTransfer: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getAuditLog: TypedContractMethod<
    [index: BigNumberish],
    [
      [string, string, bigint, string] & {
        user: string;
        action: string;
        timestamp: bigint;
        actionId: string;
      }
    ],
    "view"
  >;

  getAuditLogCount: TypedContractMethod<[], [bigint], "view">;

  getAuditLogsByAction: TypedContractMethod<
    [action: string],
    [EncryptedExamScore.AuditLogStructOutput[]],
    "view"
  >;

  getAuditLogsByUser: TypedContractMethod<
    [user: AddressLike, startIndex: BigNumberish, maxResults: BigNumberish],
    [
      [EncryptedExamScore.AuditLogStructOutput[], bigint] & {
        filteredLogs: EncryptedExamScore.AuditLogStructOutput[];
        totalCount: bigint;
      }
    ],
    "view"
  >;

  getConstants: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        maxBatchSize: bigint;
        minScore: bigint;
        maxScore: bigint;
      }
    ],
    "view"
  >;

  getEmergencyApprovalCount: TypedContractMethod<
    [actionId: BytesLike],
    [bigint],
    "view"
  >;

  getHealthStatus: TypedContractMethod<
    [],
    [
      [boolean, bigint, boolean] & {
        isHealthy: boolean;
        totalScoreCount: bigint;
        isPaused: boolean;
      }
    ],
    "view"
  >;

  getImplementation: TypedContractMethod<[], [string], "view">;

  getMyScore: TypedContractMethod<[], [string], "view">;

  getMyScoreCount: TypedContractMethod<[], [bigint], "view">;

  getTimeLockRemaining: TypedContractMethod<
    [actionId: BytesLike],
    [bigint],
    "view"
  >;

  hasApproved: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  hasScore: TypedContractMethod<[], [boolean], "view">;

  implementation: TypedContractMethod<[], [string], "view">;

  initiateOwnershipTransfer: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  scoreCount: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  setImplementation: TypedContractMethod<
    [newImplementation: AddressLike],
    [void],
    "nonpayable"
  >;

  submitBatchScores: TypedContractMethod<
    [encryptedScores: BytesLike[], inputProofs: BytesLike[]],
    [void],
    "nonpayable"
  >;

  submitScore: TypedContractMethod<
    [encryptedScore: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  timeLockedActions: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateScore: TypedContractMethod<
    [encryptedScore: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  upgradeEnabled: TypedContractMethod<[], [boolean], "view">;

  validateBatch: TypedContractMethod<
    [scores: BigNumberish[]],
    [boolean],
    "view"
  >;

  validateScore: TypedContractMethod<[score: BigNumberish], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "TIME_LOCK_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "approveEmergencyAction"
  ): TypedContractMethod<[actionId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "auditLogs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, string] & {
        user: string;
        action: string;
        timestamp: bigint;
        actionId: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "deleteMyScore"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyApprovals"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "enableUpgrades"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeOwnershipTransfer"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAuditLog"
  ): TypedContractMethod<
    [index: BigNumberish],
    [
      [string, string, bigint, string] & {
        user: string;
        action: string;
        timestamp: bigint;
        actionId: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAuditLogCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAuditLogsByAction"
  ): TypedContractMethod<
    [action: string],
    [EncryptedExamScore.AuditLogStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAuditLogsByUser"
  ): TypedContractMethod<
    [user: AddressLike, startIndex: BigNumberish, maxResults: BigNumberish],
    [
      [EncryptedExamScore.AuditLogStructOutput[], bigint] & {
        filteredLogs: EncryptedExamScore.AuditLogStructOutput[];
        totalCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getConstants"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        maxBatchSize: bigint;
        minScore: bigint;
        maxScore: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEmergencyApprovalCount"
  ): TypedContractMethod<[actionId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getHealthStatus"
  ): TypedContractMethod<
    [],
    [
      [boolean, bigint, boolean] & {
        isHealthy: boolean;
        totalScoreCount: bigint;
        isPaused: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getImplementation"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getMyScore"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getMyScoreCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTimeLockRemaining"
  ): TypedContractMethod<[actionId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasApproved"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasScore"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "implementation"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "initiateOwnershipTransfer"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "scoreCount"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "setImplementation"
  ): TypedContractMethod<
    [newImplementation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitBatchScores"
  ): TypedContractMethod<
    [encryptedScores: BytesLike[], inputProofs: BytesLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitScore"
  ): TypedContractMethod<
    [encryptedScore: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "timeLockedActions"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateScore"
  ): TypedContractMethod<
    [encryptedScore: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeEnabled"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "validateBatch"
  ): TypedContractMethod<[scores: BigNumberish[]], [boolean], "view">;
  getFunction(
    nameOrSignature: "validateScore"
  ): TypedContractMethod<[score: BigNumberish], [boolean], "view">;

  getEvent(
    key: "BatchScoresSubmitted"
  ): TypedContractEvent<
    BatchScoresSubmittedEvent.InputTuple,
    BatchScoresSubmittedEvent.OutputTuple,
    BatchScoresSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "ScoreDeleted"
  ): TypedContractEvent<
    ScoreDeletedEvent.InputTuple,
    ScoreDeletedEvent.OutputTuple,
    ScoreDeletedEvent.OutputObject
  >;
  getEvent(
    key: "ScoreSubmitted"
  ): TypedContractEvent<
    ScoreSubmittedEvent.InputTuple,
    ScoreSubmittedEvent.OutputTuple,
    ScoreSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "ScoreUpdated"
  ): TypedContractEvent<
    ScoreUpdatedEvent.InputTuple,
    ScoreUpdatedEvent.OutputTuple,
    ScoreUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "BatchScoresSubmitted(address,uint256,uint256)": TypedContractEvent<
      BatchScoresSubmittedEvent.InputTuple,
      BatchScoresSubmittedEvent.OutputTuple,
      BatchScoresSubmittedEvent.OutputObject
    >;
    BatchScoresSubmitted: TypedContractEvent<
      BatchScoresSubmittedEvent.InputTuple,
      BatchScoresSubmittedEvent.OutputTuple,
      BatchScoresSubmittedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address,uint256)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address,uint256)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "ScoreDeleted(address,uint256)": TypedContractEvent<
      ScoreDeletedEvent.InputTuple,
      ScoreDeletedEvent.OutputTuple,
      ScoreDeletedEvent.OutputObject
    >;
    ScoreDeleted: TypedContractEvent<
      ScoreDeletedEvent.InputTuple,
      ScoreDeletedEvent.OutputTuple,
      ScoreDeletedEvent.OutputObject
    >;

    "ScoreSubmitted(address,uint256,uint256)": TypedContractEvent<
      ScoreSubmittedEvent.InputTuple,
      ScoreSubmittedEvent.OutputTuple,
      ScoreSubmittedEvent.OutputObject
    >;
    ScoreSubmitted: TypedContractEvent<
      ScoreSubmittedEvent.InputTuple,
      ScoreSubmittedEvent.OutputTuple,
      ScoreSubmittedEvent.OutputObject
    >;

    "ScoreUpdated(address,uint256,uint256)": TypedContractEvent<
      ScoreUpdatedEvent.InputTuple,
      ScoreUpdatedEvent.OutputTuple,
      ScoreUpdatedEvent.OutputObject
    >;
    ScoreUpdated: TypedContractEvent<
      ScoreUpdatedEvent.InputTuple,
      ScoreUpdatedEvent.OutputTuple,
      ScoreUpdatedEvent.OutputObject
    >;

    "Unpaused(address,uint256)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
